/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamoac064b5f-amplifyt",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "apitest",
            "endpoint": "https://ynmug67p61.execute-api.us-east-1.amazonaws.com/amplifyt",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
